---
# tasks file for ansible-etcd
- name: check definition of etcd_inventory_clustergroup
  fail: msg="This play requires 'etcd_inventory_clustergroup'"
  when: etcd_inventory_clustergroup is not defined
  tags: [installation]

- name: check definition of etcd_admin_password
  fail: msg="This play requires 'etcd_admin_password'"
  when: etcd_admin_password is not defined
  tags: [installation]

## INSTALLATION ##
- name: etcd_install.yml
  include: etcd_install.yml
  when:
    ansible_distribution == 'Ubuntu'
    and ansible_distribution_release == 'trusty'
    or ansible_distribution_release == 'xenial'
  tags: [installation]

## ROLLBACK ##
- name: etcd_rollback.yml
  include: etcd_rollback.yml
  when:
    ansible_distribution == 'Ubuntu'
    and ansible_distribution_release == 'trusty'
    or ansible_distribution_release == 'xenial'
  tags: [rollback]

## TESTING ##
- name: etcd_testing.yml
  include: etcd_testing.yml
  when:
    ansible_distribution == 'Ubuntu'
    and ansible_distribution_release == 'trusty'
    or ansible_distribution_release == 'xenial'
  tags: [testing]
